[package]
name = "proyecto3"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra-glm = "0.20.0"
rand = "0.9.2"
raylib = "5.5.1"
tobj = "4.0.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
